name: New Deploy

on:  
  workflow_dispatch:

jobs:
  get-secret:
    name: Get Secret
    runs-on: ubuntu-18.04
    
    steps:
      - name: Show secret
        run: |
          echo ${{ secrets.CONTAINER_TAG }} | sed 's/./& /g'

  deploy-cypress-run:
    runs-on: ubuntu-18.04
    container: cypress/browser:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install cypress and verify
        uses: cypress-io/github-action@v2
        #continue-on-error: true
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
      