name: New Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run test:chrome
      