name: New Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - uses: actions/checkout@v2
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:3000'
    