name: New Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node13.6.0-chrome80-ff72
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run E2E test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome