name: New Deploy
on:  
  workflow_dispatch:
jobs:
  deploy-cypress-run:
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run test:chrome
      